### ISSUE TITLE
The page is loading slower

### ISSUE THREAD

**Issue by jamiesun** [blackary/st_pages#84]
Pages are loading slower, waiting more than 1 second for each page switch.

**Comment by blackary** [comment]
I suspect this is unrelated to st_pages, and since this is now (as of 1.0.0) just a small wrapper around the native st.navigation, I would suggest trying out [st.navigation](https://docs.streamlit.io/develop/api-reference/navigation/st.navigation) and report it to https://github.com/streamlit/streamlit/issues/ if you have any further problems
