### ISSUE TITLE
St-pages doesn't work properly on Streamlit Cloud environment

### ISSUE THREAD

**Issue by patrykpalej** [blackary/st_pages#85]
I have an app with a very simple structure. I use `st-pages` there and everything works fine on my server. However when I send it to the Streamlit cloud, the pages names aren't rendered properly. 

I know it may be related to environment, because the app works on my server, however maybe something can be changed to support Streamlit cloud as well?

Here is my code and deployed app:

https://github.com/patrykpalej/Real-Estate-Market-Analysis-dashboard/

https://real-estate-market-pl.streamlit.app/

Btw. I tried to setup my app with multiple combination in terms of setting PYTHONPATH, append `sys.path` etc. It looks like the behaviour was indeterministic, because sometimes it works, sometimes it doesn't and I cannot tell what's wrong and why.

**Comment by blackary** [comment]
I'm not really sure why this is happening, but I think it has something to do with the fact that importing this file actually runs some code, because if I move the connection_string code inside of the `fetch_and_preprocess` it works for me. I would recommend doing that in general -- don't make importing a module actually run code.

I would also highly recommend you look into st.secrets for your credentials, rather than using os.environment https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app/secrets-management, but that's probably unrelated.

**Comment by patrykpalej** [comment]
You mean such a change? -> https://github.com/patrykpalej/Real-Estate-Market-Analysis-dashboard/blob/master/functions/data_loading.py

I rebooted the app in the cloud after push but pages names still aren't visible. Did you mean that it works for you locally or in the cloud? In my local environment it works as well. The only problem is in the streamlit cloud.

I will try st.secrets, havn't heard about it before.

**Comment by Yelinz** [comment]
Heyo I have the same problem.
It seems to apply the layout wide but nothing else.

https://github.com/Yelinz/commute-city-triangulation/blob/777ea3f66416d21277b48713788cde1f8391bf75/main.py#L19
https://commute-triangulation.streamlit.app/

**Comment by danilo-css** [comment]
@blackary I had the same problem and solved it adding "is_section=true" at the last page of my page list. 

Seems that for it to work on Streamlit Cloud now at least 1 page has to have "is_section=true". If none have it doesn't work.

**Comment by blackary** [comment]
This is very likely resolved in the latest release of st-pages
